#ifndef RPHYS_DOMAIN_FLUID_SHARED_NEIGHBOR_SEARCH_HPP
#define RPHYS_DOMAIN_FLUID_SHARED_NEIGHBOR_SEARCH_HPP

namespace rphys { struct fluid_neighbor_search; }

#endif // RPHYS_DOMAIN_FLUID_SHARED_NEIGHBOR_SEARCH_HPP

