#ifndef RPHYS_DOMAIN_RIGID_ALGORITHMS_IMPULSE_RIGID_HPP
#define RPHYS_DOMAIN_RIGID_ALGORITHMS_IMPULSE_RIGID_HPP

namespace rphys { struct impulse_rigid_algorithm; }

#endif // RPHYS_DOMAIN_RIGID_ALGORITHMS_IMPULSE_RIGID_HPP

