#ifndef RPHYS_DOMAIN_GAS_SHARED_ADVECTION_SCHEMES_HPP
#define RPHYS_DOMAIN_GAS_SHARED_ADVECTION_SCHEMES_HPP

namespace rphys { struct gas_advection_schemes; }

#endif // RPHYS_DOMAIN_GAS_SHARED_ADVECTION_SCHEMES_HPP

