#ifndef RPHYS_COUPLING_CLOTH_FLUID_EXCHANGE_CONTRACT_HPP
#define RPHYS_COUPLING_CLOTH_FLUID_EXCHANGE_CONTRACT_HPP

namespace rphys { struct cloth_fluid_exchange_contract; }

#endif // RPHYS_COUPLING_CLOTH_FLUID_EXCHANGE_CONTRACT_HPP

