#ifndef RPHYS_COUPLING_CLOTH_RIGID_CONTACT_CONTRACT_HPP
#define RPHYS_COUPLING_CLOTH_RIGID_CONTACT_CONTRACT_HPP

namespace rphys { struct cloth_rigid_contact_contract; }

#endif // RPHYS_COUPLING_CLOTH_RIGID_CONTACT_CONTRACT_HPP

