#ifndef RPHYS_DOMAIN_CLOTH_ALGORITHMS_FEM_CLOTH_HPP
#define RPHYS_DOMAIN_CLOTH_ALGORITHMS_FEM_CLOTH_HPP

namespace rphys { struct fem_cloth_algorithm; }

#endif // RPHYS_DOMAIN_CLOTH_ALGORITHMS_FEM_CLOTH_HPP

