#ifndef RPHYS_DOMAIN_CLOTH_ALGORITHMS_PBD_CLOTH_HPP
#define RPHYS_DOMAIN_CLOTH_ALGORITHMS_PBD_CLOTH_HPP

namespace rphys { struct pbd_cloth_algorithm; }

#endif // RPHYS_DOMAIN_CLOTH_ALGORITHMS_PBD_CLOTH_HPP

