#ifndef RPHYS_DOMAIN_CLOTH_ALGORITHMS_STABLE_PD_CLOTH_HPP
#define RPHYS_DOMAIN_CLOTH_ALGORITHMS_STABLE_PD_CLOTH_HPP

namespace rphys { struct stable_pd_cloth_algorithm; }

#endif // RPHYS_DOMAIN_CLOTH_ALGORITHMS_STABLE_PD_CLOTH_HPP

