#ifndef RPHYS_DOMAIN_NEW_TEMPLATE_PIPELINE_CONTRACT_HPP
#define RPHYS_DOMAIN_NEW_TEMPLATE_PIPELINE_CONTRACT_HPP

namespace rphys { struct new_domain_pipeline_contract; }

#endif // RPHYS_DOMAIN_NEW_TEMPLATE_PIPELINE_CONTRACT_HPP

