#ifndef RPHYS_DOMAIN_GAS_ALGORITHMS_LATTICE_BOLTZMANN_HPP
#define RPHYS_DOMAIN_GAS_ALGORITHMS_LATTICE_BOLTZMANN_HPP

namespace rphys { struct lattice_boltzmann_algorithm; }

#endif // RPHYS_DOMAIN_GAS_ALGORITHMS_LATTICE_BOLTZMANN_HPP

