schema_version = "1.0.0"
id = "hinacloth"
version = "1.0.0"
name = "HinaCloth Extension"
tagline = "HinaCloth Benchmark Extension for Blender"
maintainer = "ycxiang14sep@gmail.com"
type = "add-on"
blender_version_min = "4.5.3"
license = ["MPL-2.0"]
website = "https://i.xayah.me/hinacloth"
tags = ["Physics", "Cloth Simulation", "Garment"]
