name: linux-build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ashutoshvarma/setup-ninja@v1.1

      - name: Configure (Release, tests only)
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DHINACLOTH_BUILD_VULKAN_VISUALIZER=OFF \
            -DHINACLOTH_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

